version: '3.9'
services: 
    backend:
        build: .
        ports:
            - 8001:3000
        volumes:
            - .:/app
        depends_on: 
            - db
            - redis

    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: promoter
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - .dbdata:/var/lib/mysql
        ports:
            - 3307:3306

    redis:
        image: redis:latest
        ports:
            - 6379:6379